apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: readinvoice
  labels:
    app: readinvoice
    component: backend
    version: "1.0.0"
spec:
  type: ClusterIP
  selector:
    app: readinvoice
    component: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: php-fpm
      port: 9000
      targetPort: 9000
      protocol: TCP
