CREATE TABLE IF NOT EXISTS invoices (
    id                      BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email_id                BIGINT UNSIGNED NOT NULL,
    vendor_id               BIGINT UNSIGNED DEFAULT NULL,
    invoice_number          VARCHAR(255) DEFAULT NULL,
    invoice_date            DATE DEFAULT NULL,
    due_date                DATE DEFAULT NULL,
    total_amount            DECIMAL(15,2) DEFAULT NULL,
    currency                CHAR(3) DEFAULT 'USD',
    pdf_path                VARCHAR(1024) NOT NULL,
    pdf_sha256              CHAR(64) NOT NULL,
    pdf_original_name       VARCHAR(512) DEFAULT NULL,
    ocr_raw_text            LONGTEXT DEFAULT NULL,
    extraction_confidence   DECIMAL(5,2) DEFAULT NULL,
    extraction_status       ENUM('pending','completed','failed','manual_review') DEFAULT 'pending',
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE,
    FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE SET NULL,
    INDEX idx_invoices_vendor (vendor_id),
    INDEX idx_invoices_email (email_id),
    INDEX idx_invoices_number (invoice_number),
    INDEX idx_invoices_date (invoice_date),
    INDEX idx_invoices_status (extraction_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
