apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: procom
  labels:
    app: procom
    component: frontend
    version: "1.0.0"
spec:
  type: ClusterIP
  selector:
    app: procom
    component: frontend
  ports:
    - name: http
      port: 9001
      targetPort: 9001
      protocol: TCP
