apiVersion: v1
kind: Service
metadata:
  name: mysql-router
  namespace: procom
  labels:
    app: procom
    component: mysql-router
    version: "8.4"
spec:
  type: ClusterIP
  selector:
    app: procom
    component: mysql-router
  ports:
    - name: mysql-rw
      port: 6446
      targetPort: 6446
      protocol: TCP
    - name: mysql-ro
      port: 6447
      targetPort: 6447
      protocol: TCP
